---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: torchrun-manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduling.run.ai
  resources:
  - queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunjobs/finalizers
  verbs:
  - update
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunqueues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunqueues/finalizers
  verbs:
  - update
- apiGroups:
  - torchrun.ai
  resources:
  - torchrunqueues/status
  verbs:
  - get
  - patch
  - update
