{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "torchrun-controller.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "torchrun-controller.namespace" .) }}
  labels:
    {{- include "torchrun-controller.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "torchrun-controller.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.interval }}
    path: /metrics
{{- end }} 