---
# TODO: allow arbitrary resource creation for queues with owner references
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-datasets
  namespace: default
  ownerReferences:
    - apiVersion: torchrun.ai/v1alpha1
      kind: TorchrunQueue
      name: dev
      # The UID should be set by the controller or manually after creation
      uid: 37a81f9d-af1e-4cca-b28e-a37571cf629e
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc-datasets
  resources:
    requests:
      storage: 10000000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: juicefs-checkpoints
  namespace: default
  ownerReferences:
    - apiVersion: torchrun.ai/v1alpha1
      kind: TorchrunQueue
      name: dev
      # The UID should be set by the controller or manually after creation
      uid: 37a81f9d-af1e-4cca-b28e-a37571cf629e
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: juicefs-sc-checkpoints
  resources:
    requests:
      storage: 10000000Gi
---
apiVersion: torchrun.ai/v1alpha1
kind: TorchrunQueue
metadata:
  name: dev
  namespace: default
spec:
  queue:
    name: dev
    parentQueue: default
    resources:
      cpu:
        quota: -1
        limit: -1
        overQuotaWeight: 1
      gpu:
        quota: -1
        limit: -1
        overQuotaWeight: 1
      memory:
        quota: -1
        limit: -1
        overQuotaWeight: 1
  serviceAccountName: default
  podTemplate:
    metadata:
      labels:
        queue: dev
      annotations: {}
    spec:
      hostNetwork: true
      hostIPC: true
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: trainer
          image: dream3dml/pytorch:latest
          resources:
            requests:
              nvidia.com/gpu: 8
              cpu: 64
              memory: 500Gi
              ephemeral-storage: 300Gi
            limits:
              nvidia.com/gpu: 8
              cpu: 64
              memory: 500Gi
              ephemeral-storage: 300Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: datasets
              mountPath: /jfs/datasets
            - name: checkpoints
              mountPath: /jfs/checkpoints
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Gi
        - name: datasets
          persistentVolumeClaim:
            claimName: juicefs-datasets
        - name: checkpoints
          persistentVolumeClaim:
            claimName: juicefs-checkpoints

