apiVersion: torchrun.ai/v1alpha1
kind: TorchrunQueue
metadata:
  name: dev
  namespace: default
spec:
  queue:
    name: dev
    parentQueue: default
    resources:
      cpu:
        quota: -1
        limit: -1
        overQuotaWeight: 1
      gpu:
        quota: -1
        limit: -1
        overQuotaWeight: 1
      memory:
        quota: -1
        limit: -1
        overQuotaWeight: 1
  serviceAccountName: default
  podTemplate:
    metadata:
      labels:
        queue: dev
      annotations: {}
    spec:
      hostNetwork: true
      hostIPC: true
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          effect: "NoSchedule"
      containers:
        - name: trainer
          image: dream3dml/pytorch:latest
          resources:
            requests:
              nvidia.com/gpu: 8
              cpu: 64
              memory: 500Gi
              ephemeral-storage: 300Gi
            limits:
              nvidia.com/gpu: 8
              cpu: 64
              memory: 500Gi
              ephemeral-storage: 300Gi
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: datasets
              mountPath: /jfs/datasets
            - name: checkpoints
              mountPath: /jfs/checkpoints
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 512Gi
        - name: datasets
          persistentVolumeClaim:
            claimName: juicefs-pvc-datasets
        - name: checkpoints
          persistentVolumeClaim:
            claimName: juicefs-pvc-checkpoints
  workspaceStorage:
    size: 1Gi
    source: zip
    storageClass: csi-s3
  distributed:
    rdzvBackend: etcd-v2
    rdzvEndpoint: etcd.etcd-system.svc.cluster.local:2379